TRUNCATE TABLE D_RETAIL_TIME_YEAR_T;

INSERT INTO RETAIL_DWH.TARGET.D_RETAIL_TIME_YEAR_T (
	ID
	,YEAR_KY
	,YEAR_START_DATE
	,YEAR_END_DATE
	,OPEN_CLOSE_CD
	,ROW_INSRT_TMS
	,ROW_UPDT_TMS
	)
SELECT DISTINCT (TO_CHAR(MY_DATE, 'YYYY'))
	,(TO_CHAR(MY_DATE, 'YYYY'))
	,TRUNC(MY_DATE, 'YEAR')
	,LAST_DAY(MY_DATE, 'YEAR')
	,1
	,sysdate()
	,sysdate()
FROM (
	SELECT DATEADD(DAY, SEQ4(), TO_DATE('2019', 'YYYY')) AS MY_DATE
	FROM TABLE (GENERATOR(ROWCOUNT => 3650))
	)
ORDER BY 1;

TRUNCATE TABLE D_RETAIL_TIME_HALF_YEAR_T;

INSERT INTO RETAIL_DWH.TARGET.D_RETAIL_TIME_HALF_YEAR_T (
	ID
	,HALF_YEAR_KY
	,YEAR_KY
	,HALF_YEAR_START_DATE
	,HALF_YEAR_END_DATE
	,OPEN_CLOSE_CD
	,ROW_INSRT_TMS
	,ROW_UPDT_TMS
	)
SELECT DISTINCT CASE 
		WHEN MONTH(MY_DATE) < 7
			THEN YEAR(MY_DATE) || 'Half-Year 01'
		ELSE YEAR(MY_DATE) || ' Half-Year 02'
		END
	,CASE 
		WHEN MONTH(MY_DATE) < 7
			THEN YEAR(MY_DATE) || '01'
		ELSE YEAR(MY_DATE) || '02'
		END
	,YEAR(MY_DATE)
	,CASE 
		WHEN MONTH(MY_DATE) < 7
			THEN TRUNC(TO_DATE(YEAR(MY_DATE) || '01', 'YYYYMM'), 'MONTH')
		ELSE TRUNC(TO_DATE(YEAR(MY_DATE) || '06', 'YYYYMM'), 'MONTH')
		END
	,CASE 
		WHEN MONTH(MY_DATE) < 7
			THEN LAST_DAY(TO_DATE(YEAR(MY_DATE) || '06', 'YYYYMM'), 'MONTH')
		ELSE LAST_DAY(TO_DATE(YEAR(MY_DATE) || '12', 'YYYYMM'), 'MONTH')
		END
	,1
	,sysdate()
	,sysdate()
FROM (
	SELECT DATEADD(DAY, SEQ4(), TO_DATE('2019', 'YYYY')) AS MY_DATE
	FROM TABLE (GENERATOR(ROWCOUNT => 3650))
	)
ORDER BY 1;

TRUNCATE TABLE D_RETAIL_TIME_QUARTER_T;

INSERT INTO RETAIL_DWH.TARGET.D_RETAIL_TIME_QUARTER_T (
	ID
	,QUARTER_KY
	,YEAR_KY
	,HALF_YEAR_KY
	,QUARTER_START_DATE
	,QUARTER_END_DATE
	,OPEN_CLOSE_CD
	,ROW_INSRT_TMS
	,ROW_UPDT_TMS
	)
SELECT DISTINCT YEAR(MY_DATE) || 'QUARTER 0' || QUARTER(MY_DATE)
	,YEAR(MY_DATE) || '0' || QUARTER(MY_DATE)
	,YEAR(MY_DATE)
	,CASE 
		WHEN MONTH(MY_DATE) < 7
			THEN YEAR(MY_DATE) || '01'
		ELSE YEAR(MY_DATE) || '02'
		END
	,TRUNC(MY_DATE, 'QTR')
	,LAST_DAY(MY_DATE, 'QTR')
	,1
	,sysdate()
	,sysdate()
FROM (
	SELECT DATEADD(DAY, SEQ4(), TO_DATE('2019', 'YYYY')) AS MY_DATE
	FROM TABLE (GENERATOR(ROWCOUNT => 3650))
	)
ORDER BY 1;

TRUNCATE TABLE D_RETAIL_TIME_MONTH_T;

INSERT INTO RETAIL_DWH.TARGET.D_RETAIL_TIME_MONTH_T (
	ID
	,MONTH_KY
	,MONTH_DESC
	,QUARTER_KY
	,YEAR_KY
	,HALF_YEAR_KY
	,MONTH_START_DATE
	,MONTH_END_DATE
	,OPEN_CLOSE_CD
	,ROW_INSRT_TMS
	,ROW_UPDT_TMS
	)
SELECT DISTINCT TO_CHAR(MY_DATE, 'YYYY') ||' Month '||TO_CHAR(MY_DATE,'MM')
	,TO_CHAR(MY_DATE, 'YYYYMM')
    ,TO_CHAR(MY_DATE,'MMMM')
	,YEAR(MY_DATE) || '0' || QUARTER(MY_DATE)
	,YEAR(MY_DATE)
	,CASE 
		WHEN MONTH(MY_DATE) < 7
			THEN YEAR(MY_DATE) || '01'
		ELSE YEAR(MY_DATE) || '02'
		END
	,TRUNC(MY_DATE, 'MONTH')
	,LAST_DAY(MY_DATE, 'MONTH')
	,1
	,sysdate()
	,sysdate()
FROM (
	SELECT DATEADD(DAY, SEQ4(), TO_DATE('2019', 'YYYY')) AS MY_DATE
	FROM TABLE (GENERATOR(ROWCOUNT => 3650))
	)
ORDER BY 1;

TRUNCATE TABLE D_RETAIL_TIME_DAY_T;

INSERT INTO RETAIL_DWH.TARGET.D_RETAIL_TIME_DAY_T (
	ID
	,DAY_KY
	,MONTH_KY
	,QUARTER_KY
	,YEAR_KY
	,HALF_YEAR_KY
	,DAY_START_TIME
	,DAY_END_TIME
	,OPEN_CLOSE_CD
	,ROW_INSRT_TMS
	,ROW_UPDT_TMS
	)
SELECT DISTINCT MY_DATE
	,TO_CHAR(MY_DATE, 'YYYYMMDD')
	,TO_CHAR(MY_DATE, 'YYYYMM')
	,YEAR(MY_DATE) || '0' || QUARTER(MY_DATE)
	,YEAR(MY_DATE)
	,CASE 
		WHEN MONTH(MY_DATE) < 7
			THEN YEAR(MY_DATE) || '01'
		ELSE YEAR(MY_DATE) || '02'
		END
	,MY_DATE || ' 07:00:00'
	,MY_DATE || ' 21:00:00'
	,1
	,sysdate()
	,sysdate()
FROM (
	SELECT DATEADD(DAY, SEQ4(), TO_DATE('2019', 'YYYY')) AS MY_DATE
	FROM TABLE (GENERATOR(ROWCOUNT => 3650))
	)
ORDER BY 1;
