create or replace database RETAIL_DWH;
create or replace schema SOURCE;

create or replace TABLE SOURCE.CATEGORY (
	ID NUMBER(38,0) NOT NULL,
	CATEGORY_DESC VARCHAR(1024),
	primary key (ID)
);
create or replace TABLE COUNTRY (
	ID NUMBER(38,0) NOT NULL,
	COUNTRY_DESC VARCHAR(256),
	primary key (ID)
);
create or replace TABLE CUSTOMER (
	ID NUMBER(38,0) NOT NULL,
	CUSTOMER_FIRST_NAME VARCHAR(256),
	CUSTOMER_MIDDLE_NAME VARCHAR(256),
	CUSTOMER_LAST_NAME VARCHAR(256),
	CUSTOMER_ADDRESS VARCHAR(256),
	primary key (ID)
);
create or replace TABLE SUBCATEGORY (
	ID NUMBER(38,0) NOT NULL,
	CATEGORY_ID NUMBER(38,0),
	SUBCATEGORY_DESC VARCHAR(256),
	primary key (ID),
	foreign key (CATEGORY_ID) references RETAIL_DWH.SOURCE.CATEGORY(ID)
);
create or replace TABLE PRODUCT (
	ID NUMBER(38,0) NOT NULL,
	SUBCATEGORY_ID NUMBER(38,0),
	PRODUCT_DESC VARCHAR(256),
	primary key (ID),
	foreign key (SUBCATEGORY_ID) references RETAIL_DWH.SOURCE.SUBCATEGORY(ID)
);


create or replace TABLE REGION (
	ID NUMBER(38,0) NOT NULL,
	COUNTRY_ID NUMBER(38,0),
	REGION_DESC VARCHAR(256),
	primary key (ID),
	foreign key (COUNTRY_ID) references RETAIL_DWH.SOURCE.COUNTRY(ID)
);
create or replace TABLE STORE (
	ID NUMBER(38,0) NOT NULL,
	REGION_ID NUMBER(38,0),
	STORE_DESC VARCHAR(256),
	primary key (ID),
	foreign key (REGION_ID) references RETAIL_DWH.SOURCE.REGION(ID)
);
create or replace TABLE SALES (
	ID NUMBER(38,0) NOT NULL,
	STORE_ID NUMBER(38,0) NOT NULL,
	PRODUCT_ID NUMBER(38,0) NOT NULL,
	CUSTOMER_ID NUMBER(38,0),
	TRANSACTION_TIME TIMESTAMP_NTZ(9),
	QUANTITY NUMBER(38,0),
	AMOUNT NUMBER(20,2),
	DISCOUNT NUMBER(20,2),
	primary key (ID),
	foreign key (STORE_ID) references RETAIL_DWH.SOURCE.STORE(ID),
	foreign key (PRODUCT_ID) references RETAIL_DWH.SOURCE.PRODUCT(ID),
	foreign key (CUSTOMER_ID) references RETAIL_DWH.SOURCE.CUSTOMER(ID)
);

CREATE OR REPLACE FILE FORMAT ETL
	TYPE = csv
	FIELD_DELIMITER = '|'
	FIELD_OPTIONALLY_ENCLOSED_BY = ''''
	NULL_IF = ('NULL')
;